### ISSUE TITLE
xms argument 

### ISSUE THREAD

**Issue by imtomjorge** [SchokkerIT/GameDash#1]
When we launch a server, automatically the worker hosted on any node is using more than 100% of memory allocated by default. It could be a good idea to define as java argument -Xms as a quarter of memory allocated.
Eg. 1024MB server ram --> GD automatically define -Xms arg to 256Mo...

**Comment by Jesse-Schokker** [comment]
Implemented `/usr/lib/jvm/java-11-openjdk-amd64/bin/java -Xmx512M -Xms128M -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -jar paper_1.16.1.jar nogui`
