### ISSUE TITLE
During installation of GD install bash, install docker first before asking for all the domain information

### ISSUE THREAD

**Issue by minecraftdan1234** [SchokkerIT/GameDash#11]
**Describe the solution you'd like**
During installation of GD install bash, complete the installation of docker first before asking for all the domain information such as the frontend domains, mysql settings and anything else. During this break/stop in the script, the user can do docker login by opening another session and running `docker login`.

**Describe alternatives you've considered**
Implement the docker login and password entry into the script when it requires them.

**Additional context**
I find that the script automatically installs docker and fails to pull the images (obviously since I am not logged in yet) and causes me a bit of an issue since I have to docker pull and such else to make sure they are all updated. I don't have enough time since the script runs fast to run docker login in another session before the script starts pulling container data.

**Comment by aleforge** [comment]
You can just run the script again and it will pull the images after you use docker login. This won't be an issue in the production release when the images are public.

**Comment by minecraftdan1234** [comment]
That does make sense, appreciate it.
