### ISSUE TITLE
Inconsistent titles - Should be above the placeholder not below

### ISSUE THREAD

**Issue by minecraftdan1234** [SchokkerIT/GameDash#18]
**Describe the bug**
Inconsistent titles - The title should be above the placeholder and not below it unless this was intentional UI design. Some people may question it....

**To Reproduce**
1. Infrastructure > Node > Manage > Services AND Dependencies AND Processes AND File System. (Everywhere basically)
2. Title is below the placeholder and not above.
![image](https://user-images.githubusercontent.com/57631710/87718160-31f8a280-c7a9-11ea-8e4a-f2730d82b75f.png)
![image](https://user-images.githubusercontent.com/57631710/87718188-358c2980-c7a9-11ea-9ed5-ed38bb59e6f6.png)
etc...

**Expected behavior**
Switch them around.

**Screenshots**
N/A. See above.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Frontend Version 7

**Comment by Jesse-Schokker** [comment]
This is an intentional design decision.
