### ISSUE TITLE
FAQ Article Creation Text Issues

### ISSUE THREAD

**Issue by BenB289** [SchokkerIT/GameDash#2]
**Describe the bug**
On the Admin page for Category creation in the FAQ page it shows "{ucfirst:faq.category.no_categories_created_yet}", once you create a category and go to the Articles page you get "{ucfirst:faq.article.no_articles_found}". When you go to create an article it shows "{UCFIRST:COMMON.PREVIEW} instead of just "Preview".

**To Reproduce**
1. Go to Admin, then FAQ, Categories to see the first one.
2. Go to Articles, to see the second.
3. Click Create on the Articles page, to see the third one.

**Expected behavior**
Should say something along the lines of: "No Categories Found", "No Articles Found", "Preview".

**Screenshots**
https://i.imgur.com/fysFVrj.png
https://i.imgur.com/IdURNIP.png
https://i.imgur.com/Dl0QYla.png

**Desktop (please complete the following information):**
 - OS: Windows 10 (Up to date)
 - Browser: Chrome (Up to date)
 - Version: Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by Jesse-Schokker** [comment]
Seems to be a caching issue. Please clear your local storage for the domain and try reload.
