### ISSUE TITLE
SEVERE: Creating a new instance states "Error" in notification bar but is actually installed and awaiting setup.

### ISSUE THREAD

**Issue by minecraftdan1234** [SchokkerIT/GameDash#20]
**Describe the bug**
Creating a new instance states "Error" in notification popup bar but is actually installed and awaiting setup.
![image](https://user-images.githubusercontent.com/57631710/87719749-c95ef500-c7ab-11ea-86f5-ba13ac882dad.png)
![image](https://user-images.githubusercontent.com/57631710/87719778-d7147a80-c7ab-11ea-80a2-74916a535bc3.png)

**To Reproduce**
1. Select instances on left hand side
![image](https://user-images.githubusercontent.com/57631710/87719887-fe6b4780-c7ab-11ea-8101-2ef19c466d58.png)
2. Enter information required then click create
![image](https://user-images.githubusercontent.com/57631710/87719930-117e1780-c7ac-11ea-8886-54d7042380cc.png)
![image](https://user-images.githubusercontent.com/57631710/87719933-12af4480-c7ac-11ea-935e-c8c84ee3fed5.png)
3. See error popup and created popup
![image](https://user-images.githubusercontent.com/57631710/87719942-1642cb80-c7ac-11ea-9a59-9b257416563e.png)
4. Server is actually installed if you click `Instances` again on the left hand side and then the server to configure it for setup
![image](https://user-images.githubusercontent.com/57631710/87720083-4c804b00-c7ac-11ea-99db-9ae8870125ed.png)

**Expected behavior**
Should say success - ready for setup or something.

**Screenshots**
N/A - See above.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Frontend Version 7

**Comment by Jesse-Schokker** [comment]
Fixed. Thanks for reporting.
