### ISSUE TITLE
Java issue with some Spigot version

### ISSUE THREAD

**Issue by imtomjorge** [SchokkerIT/GameDash#21]
**Describe the bug**
By default, GD is offering Paper and Vanilla. We wanted to install Spigot, and we got the following error
https://pastebin.com/bnW1UuwS

After these errors logs, relay and infrastructure node aren't reachable.

**To Reproduce**
1. Download any Spigot version 
2. Upload it via SFTP
3. Set your Spigot jar file as "default jar file"
4. See error on console 

**Additional context**
I'm available if you need more informations.

Update:
There is no issue with Spigot 1.16.1

**Comment by Jesse-Schokker** [comment]
Not an issue related to GameDash.
