### ISSUE TITLE
Can't add any asset to themes

### ISSUE THREAD

**Issue by imtomjorge** [SchokkerIT/GameDash#23]
**Describe the bug**
We can't add both logos (login page, and navbar) on all themes.

**To Reproduce**
1. Try to modify your theme
2. Then click on "assets"
3. There is no add asset button

**Expected behavior**
It may offer any button, or CTA to add a default logo.

**Screenshots**
https://global.s3.fr-par.scw.cloud/gdissuethemes.png

**Additional context**

**Comment by Jesse-Schokker** [comment]
Frontend UI bug rather than a missing feature. Solved in next update.
