### ISSUE TITLE
Can't use web file uploader

### ISSUE THREAD

**Issue by imtomjorge** [SchokkerIT/GameDash#25]
**Describe the bug**
We can't upload any file via the file uploader on any server

**To Reproduce**
1. Go your instance management page
2. Click on 'file system'
3. Scroll down to 'manager'
4. Try to drop a file on the file explorer
5. Check your web browser console (available below)

**Expected behavior**
The file may be uploaded without any issue.

**Screenshots**
https://global.s3.fr-par.scw.cloud/gdissue/gdissue1.png
https://global.s3.fr-par.scw.cloud/gdissue/gdissue2.png

**Browser**
-Firefox 78.0.1 (64 bits)
-Chrome 84.0.4147.89 (64 bits)

**Additional context**
Tried with Chrome and Firefox on macOS 10.15.3

**Comment by Jesse-Schokker** [comment]
Seems the default PHP configuration shipped with the Docker image has an incorrect max value set for body length.
